apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:h2nfXvi7guWGDg5VrAsC/7PdXFhSZYMcy6y3c3bdG+vFSP4ynp6nbw==,iv:HlLuXbh3/dnoC0dU70qZgO49W/0GFCT54Cggb0HcKWg=,tag:ovCbEqPWJ2ZFtBvKZ1WPgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZzB4aWVZYXRRMWh5Rmg2
            VFhWKzhQbGhNUnd2VWFWbGNVNGpkZktkeWk0CkRITUUvcDBHNUFsQURRamJmUVYr
            cFNrRFNhK0plYjdjVk9mM3BadStnREEKLS0tIFdTOVd3Z1FoRnlRZmRLWGZoMUZq
            SVdyQTZ5NGtyM2FFbzR6cG9Ra280TlUK+/tyI1+rrmzSHY8I3UoIzmFko6Db0/yR
            YkDI9fo2zTVdGmNyJWpBrn6f5dEyt+yEcHuXgTagiZCiRwrottEbMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-31T17:17:15Z"
    mac: ENC[AES256_GCM,data:Tqc6AQy4TjrWm4A6fj3/k+NTiSdelbKjqldfDPII+On5jrQ0x75Eb3VJ1NMyjcVPM92fyZSrvBlUd9gVHBN1+Xupswz97+b1184kUGobedghh/2zK90kDLNLeOX9675e/nTzZ2qSOvH5ARYuiW1TKnWoDH2jSQ64GtBxj+ZhGU8=,iv:5yjp08oykOH9eBGB51z7kZWtWVn2Rja6fJIpaMXPeGE=,tag:VsSC/5KJpganSxOVdAjqcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
