apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WL0i+sf8ndHUwqlapEtNe2ztN9D+cA60,iv:s5LiX4/WpZqwvnTlShMY4MduyRInS3WUeDYyM/ts9LA=,tag:P5OdlHBSUVStcQxDSIKAxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYnFaeEtSRUNEa05yR29J
            aDBEVXBnNnZhN0xMbmZ6TlpNN2I0b3VpQ1VjClNhSHFIWXdXTTVHSTNPM2J0V3U5
            VzB5KzlMMkJ1VkVuT3c2S0dzMGU2WUkKLS0tIGR0Vk1vTWJ3UER5ZW03dHBZeWlw
            cUhIb2l5Q1pGbWhvL0R1RjBSYmJMcDAKyTT5zqbMVCiyl2qdwdLM/AaY5XrGUq9o
            riuOcr2MmfkyTZAqvIB5lQs8IsEhcLxpVD7IqP3UB5JrGYU/l6FwtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-31T17:17:15Z"
    mac: ENC[AES256_GCM,data:18ugHxTAmvkgTzDv1cbT5ICBdVpduTUV6ei6EGdrwyG/MCd9yteJN84UJ0pGKEamVBJ8XJ2jGFPPscpeUIvN+0oSGrJuAFa2w9M5qL0w7oaSaPR3LpHEXpz/8LkwwE0DRhaTIU83FFbJBm66y6VSCz3AUMAxY5buQzMILkypz1s=,iv:D8OwbyjuPUkDTBqv3n5P1LpSP083HufRYtr9T8Hy7VQ=,tag:cTSb/eXtYBazzklvCfmDVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
